# Generated by Django 4.2.5 on 2023-10-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('image_url', models.CharField(max_length=512)),
                ('starting_price', models.IntegerField()),
                ('category', models.CharField(choices=[('No Category Listed', 'No category'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics')], default='No Category Listed', max_length=18)),
                ('description', models.CharField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
