# Generated by Django 4.2.5 on 2023-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
