# Generated by Django 4.2.5 on 2023-10-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_created_at_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='origin',
            new_name='listing',
        ),
    ]
