# Generated by Django 4.2.5 on 2023-10-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_listing_remove_listings_user_delete_bids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('No Category Listed', 'No category'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Cooking', 'Cooking')], default='No Category Listed', max_length=18),
        ),
    ]
