# Generated by Django 4.2.5 on 2023-10-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
